services:
  # Streamlit Web App Service
  - type: web
    name: twitch-autofarmer-web
    env: python
    buildCommand: chmod +x render-build.sh && ./render-build.sh && poetry install
    startCommand: poetry run streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: DATA_FILE_PATH
        value: /var/data/farming_data.json
      - key: RENDER
        value: true
  
  # Discord Bot Worker Service
  - type: worker
    name: twitch-autofarmer-discord
    env: python
    buildCommand: chmod +x render-build.sh && ./render-build.sh && poetry install
    startCommand: poetry run python run_discord_bot.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: DATA_FILE_PATH
        value: /var/data/farming_data.json
      - key: RENDER
        value: true
      - key: DISCORD_TOKEN
        sync: false # This will be a secret you set in the Render dashboard
      - key: DISCORD_GUILD_ID
        sync: false # Optional: This will be a secret you set in the Render dashboard